ckpt_path: "../pretrained_models/lavie_vsr.pt"
pretrained_path: "../pretrained_models"
input_path: "../results/base"
output_path: "../results/vsr"
noise_level: 50
guidance_scale: 5
inference_steps: 50
